import type { Metadata } from "next";
import "./globals.css";
import { lato } from '@/app/ui/fonts';
import Banner from "./ui/banner";
import Header from "./ui/header";
import Footer from "./ui/footer";
import ScrollToTopButton from "./ui/scroll-to-top";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { AppProvider } from "./context/AppContext";
import Chat from "./ui/chat";
import Navbar from "./ui/navbar";
import ClientWrapper from "./ui/client-wrapper";

export const metadata: Metadata = {
  title: "Share And Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={`${lato.className} antialiased`}>
          <main>
            <div className={`${lato.className} antialiased fixed w-screen top-0 z-10 flex flex-col`}>
              <ToastContainer />
              <Banner />
              <Navbar />
              <Header />
            </div>

            <ClientWrapper>
              {children}
            </ClientWrapper>

            <div className={`${lato.className} antialiased bottom-0 z-10 flex flex-col bg-black`}>
              <Footer />
            </div>

            <ScrollToTopButton />

            <Chat />
          </main>
        </body>
      </html>
    </AppProvider>
  );
}