import type { Metadata } from "next";
import "./globals.css";
import { lusitana } from '@/app/ui/fonts';
import Banner from './ui/banner';
import Navbar from './ui/navbar';
import Header from "./ui/header";
import Footer from "./ui/footer";
import ScrollToTopButton from "./ui/scroll-to-top";

export const metadata: Metadata = {
  title: "Share And Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lusitana.className} antialiased`}>
        <main>
          <div className={`${lusitana.className} antialiased fixed w-screen top-0 z-10 flex flex-col`}>
            <Banner />
            <Navbar />
            <Header />
          </div>

          <div className="mt-44">
            <div className=" overflow-y-hidden min-h-[745px] h-auto z-9">
              {children}
            </div>
          </div>

          <div className={`${lusitana.className} antialiased bottom-0 z-10 flex flex-col bg-gray-900`}>
            <Footer />
          </div>

          <ScrollToTopButton />
        </main>
      </body>
    </html>
  );
}