import type { Metadata } from "next";
import OrderStepper from "../ui/order/stepper";

export const metadata: Metadata = {
    title: "Share And Care",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div>
            <OrderStepper />

            <div>
                {children}
            </div>
        </div>
    );
}